### ISSUE TITLE
execute[resolvconf -u] should trigger :immediately

### ISSUE THREAD

**Issue by jperville** [chr4-cookbooks/resolvconf#10]
With version 0.2.6 of this cookbook, using the `resolvconf` LWRP would result in `resolvconf -u` being invoked when the LWRP has converged.

As of version 0.2.8, the `resolvconf -u` command is invoked as a delayed notification, which means the `/etc/resolv.conf` will only be updated at the end of the chef-run.

As a consequence, any recipe which expects the `/etc/resolv.conf` file to be updated immediately will fail, unless I use a very ugly workaround like this:

```ruby
resolvconf 'samba' do
  head       resolvconf_head.strip
  nameserver helper.dns_forwarders
  search     helper.dns_domain
  clear_dns_from_interfaces false
  notifies :run, 'execute[resolvconf -u]', :immediately
end

execute 'resolvconf -u' do
  action :nothing
end
```

EDIT: I believe that the culprit is https://github.com/chr4-cookbooks/resolvconf/commit/eb2907271f7ea4e9b8118e7c06d7eaa808262564 from PR #9.

**Comment by chr4** [comment]
Thanks for spotting. This sounds indeed like an issue we want to fix.
Closing this in favor of #11
