### ISSUE TITLE
Deprecated features used in resources/default.rb

### ISSUE THREAD

**Issue by vskubriev** [chr4-cookbooks/resolvconf#14]
I hope upgrading cookbook to latest version helps. But unfotunately.

```
Deprecated features used!
  Default value "true" is invalid for property clear_dns_from_interfaces of resource resolvconf. In Chef 13 this will become an error: Option clear_dns_from_interfaces must be a kind of [TrueClass, FalseClass]!  You passed "true".. at 1 location:
    - /var/chef/cache/cookbooks/resolvconf/resources/default.rb:31:in `class_from_file'
```

I don't write a complex cookbooks, therefore cannot create pull.

I you think this is easy bug, please fix it manually.

Thank you.

**Comment by chr4** [comment]
Mmh, the actual valrue is `true` not `"true"`. I'm not sure why Chef complains here, as it is actually a boolean. Maybe something changed and one is not supposed to use `[TrueClass, FalseClass]` anymore?

Hints apprechiated.

**Comment by strong-code** [comment]
(somewhat) related to this is my recent PR: https://github.com/chr4-cookbooks/resolvconf/pull/20

This addresses the deprecation warning, which is now a fully-fledged error in Chef 13.

**Comment by chr4** [comment]
Closing this in favor of #20
