### ISSUE TITLE
Cookbook runs even on unsupported systems

### ISSUE THREAD

**Issue by axelrtgs** [chr4-cookbooks/resolvconf#15]
the cookbook runs when included in a role run list consisting of mixed nodes (I.E. Ubuntu and windows).
Expected behavior would be to test and not run if not Debian based platform since this is only compatible with Debian.

i fixed this in a local copy by adding:

case node['platform_family']
when "debian"

at the begining of default.rb recipe and then:

end

at the end of the file so it only runs when on debian systems removing the compatibility issue with windows.

**Comment by axelrtgs** [comment]
added changes to fork and created a pull request with changes:

https://github.com/chr4-cookbooks/resolvconf/pull/16

**Comment by chr4** [comment]
Closing this in Favor of the pull-request
